import './globals.css'
import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import type { NextFont } from 'next/dist/compiled/@next/font'
import React from 'react'

const inter:NextFont = Prompt({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <head>
        <title>FCV HelpDesk</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
